**Uppgift 6**


Presenterar flera olika program. Det första är vad man ofta kallar 'brute force' dvs att man gör beräkningen enkel och rakt fram, det kan ta rätt mycket körtid men lite tänke-tid.

I det första programmet körs 2 loopar. Den ena från 1 till 100 (max) den andra från 1 till 100. Vi får då naturligtvis alla möjliga fall då $x+y+z \leq 100$. Men vi får också en massa fall som egentligen inte är intressanta att testa. Med testa menas satsen `z2/s == s`. För att fundera lite över antalet tester som görs så räknas de med räknaren `c`, och skrivs ut på slutet.

In [1]:
# Programmet gör inte riktigt vad det ska göra men finns här ändå.
# Det testar många fler möjligheter och samma tre tal mer än en gång.

import math as m

max = 100
c = 0

for x in range(1, max + 1):
    for y in range(1, max + 1):
        z2 = x*x + y*y
        s = int(m.sqrt(z2))
        c += 1
        if z2/s == s:
            #print(x**2, y**2, z2)
            print(x, y, s)

print("Undersökt ", c, " tal")

3 4 5
4 3 5
5 12 13
6 8 10
7 24 25
8 6 10
8 15 17
9 12 15
9 40 41
10 24 26
11 60 61
12 5 13
12 9 15
12 16 20
12 35 37
13 84 85
14 48 50
15 8 17
15 20 25
15 36 39
16 12 20
16 30 34
16 63 65
18 24 30
18 80 82
20 15 25
20 21 29
20 48 52
20 99 101
21 20 29
21 28 35
21 72 75
24 7 25
24 10 26
24 18 30
24 32 40
24 45 51
24 70 74
25 60 65
27 36 45
28 21 35
28 45 53
28 96 100
30 16 34
30 40 50
30 72 78
32 24 40
32 60 68
33 44 55
33 56 65
35 12 37
35 84 91
36 15 39
36 27 45
36 48 60
36 77 85
39 52 65
39 80 89
40 9 41
40 30 50
40 42 58
40 75 85
40 96 104
42 40 58
42 56 70
44 33 55
45 24 51
45 28 53
45 60 75
48 14 50
48 20 52
48 36 60
48 55 73
48 64 80
48 90 102
51 68 85
52 39 65
54 72 90
55 48 73
56 33 65
56 42 70
56 90 106
57 76 95
60 11 61
60 25 65
60 32 68
60 45 75
60 63 87
60 80 100
60 91 109
63 16 65
63 60 87
63 84 105
64 48 80
65 72 97
66 88 110
68 51 85
69 92 115
70 24 74
72 21 75
72 30 78
72 54 90
72 65 97
72 96 120
75 40 85
75 100 125
76 57 95
77 36 85
80 18 82
80 39 89
80 60 100
80 84 116
84 13 85
84 35 91
84 63 105
84 80 116
88 66 110
90 48 102
90 56 106
91 60 109
92 69 115
96 28 100
96 40 104
96 72 120
99 20 101
100 75 125
Undersökt  10000  tal

Vi undersöker således $100 \cdot 100 = 10000$ tal.

I nästa program försöker vi göra det bättre. Om x=1 så behöver vi bara undersöka y=1 till y=99 så att summan av x och y är under 100. Om x=2 behöver vi bara undersöka y=1 till y=98 osv. Övre gränsen för y är max-x, vilket blir max-x+1 i range().

In [2]:
# Lite bättre men x+y+z är ibland större än 100

import math as m

max = 100
c = 0
for x in range(1, max + 1):
    for y in range(1, max - x + 1):  # Ändrat denna gräns
        z2=x*x + y*y
        s=int(m.sqrt(z2))
        c += 1
        if z2/s == s:
            print(x, y, s)
print("Undersökt ", c, " tal")

3 4 5
4 3 5
5 12 13
6 8 10
7 24 25
8 6 10
8 15 17
9 12 15
9 40 41
10 24 26
11 60 61
12 5 13
12 9 15
12 16 20
12 35 37
13 84 85
14 48 50
15 8 17
15 20 25
15 36 39
16 12 20
16 30 34
16 63 65
18 24 30
18 80 82
20 15 25
20 21 29
20 48 52
21 20 29
21 28 35
21 72 75
24 7 25
24 10 26
24 18 30
24 32 40
24 45 51
24 70 74
25 60 65
27 36 45
28 21 35
28 45 53
30 16 34
30 40 50
32 24 40
32 60 68
33 44 55
33 56 65
35 12 37
36 15 39
36 27 45
36 48 60
39 52 65
40 9 41
40 30 50
40 42 58
42 40 58
42 56 70
44 33 55
45 24 51
45 28 53
48 14 50
48 20 52
48 36 60
52 39 65
56 33 65
56 42 70
60 11 61
60 25 65
60 32 68
63 16 65
70 24 74
72 21 75
80 18 82
84 13 85
Undersökt  4950  tal

Vi undersöker nu cirka hälften så många tal. Antalet ges av en aritmetisk talföljd. $99+98+97+...+52+51+50+49+48+...+3+2+1 = 100\cdot49+50=4950$


I nästa program lägger vi in en if-sats. Detta ger ett nytt test men är mindre krävande för datorn. Vi gör den i 2 varianter. En med 2 if och en med en och-sats.

In [3]:
# Ännu lite bättre. Vi testar inte om det visar sig att z gör att vi får en summa större än 100
# Observera att vi även får med de som bara är multiplar av varandra tex. (4,3,5) och (8,6,10).

import math as m

max = 100
c = 0
l = 0

for x in range(1, max + 1):
    for y in range(1, max - x + 1):
        l += 1
        z2 = x*x + y*y
        z = int(m.sqrt(z2))
        if x+y+z <= max:
            c += 1
            if z2/z == z:
                print(x, y, z)
print("Undersökt ", c, " tal")
print("Loopat ", l, " tal")

3 4 5
4 3 5
5 12 13
6 8 10
7 24 25
8 6 10
8 15 17
9 12 15
9 40 41
10 24 26
12 5 13
12 9 15
12 16 20
12 35 37
15 8 17
15 20 25
15 36 39
16 12 20
16 30 34
18 24 30
20 15 25
20 21 29
21 20 29
21 28 35
24 7 25
24 10 26
24 18 30
24 32 40
28 21 35
30 16 34
32 24 40
35 12 37
36 15 39
40 9 41
Undersökt  1513  tal
Loopat  4950  tal

Nu blev det bara 1513 tal om vi först sållar med ett enklare test. Det är fortfarande 4950 tal som på något sätt testas, men bara 1513 som gör det tidskrävande testet.

Nedan följer varianten med och-sats i stället för 2 if:

```
for x in range(1, max + 1):
    for y in range(1, max - x + 1):
        l += 1
        z2 = x*x + y*y
        z = int(m.sqrt(z2))
        if x+y+z <= max and z2/z == z:
                print(x, y, z)
```

Man kan också tänka att x och y ska behandlas symmetriskt. Då behöver man bara undersöka x upp till 50 (max/2).

In [4]:
import math as m

max = 100
c = 0
l = 0

for x in range(1, int(max/2)):
    for y in range(1, max - x + 1):
        l += 1
        z2 = x*x + y*y
        z = int(m.sqrt(z2))
        if x+y+z <= max:
            c += 1
            if z2/z == z:
                print(x, y, z)
print("Undersökt ", c, " tal")
print("Loopat ", l, " tal")

3 4 5
4 3 5
5 12 13
6 8 10
7 24 25
8 6 10
8 15 17
9 12 15
9 40 41
10 24 26
12 5 13
12 9 15
12 16 20
12 35 37
15 8 17
15 20 25
15 36 39
16 12 20
16 30 34
18 24 30
20 15 25
20 21 29
21 20 29
21 28 35
24 7 25
24 10 26
24 18 30
24 32 40
28 21 35
30 16 34
32 24 40
35 12 37
36 15 39
40 9 41
Undersökt  1513  tal
Loopat  3675  tal

Man ser ingen ändring i antalet undersökta tal men man har ändå en mindre mängd i looparna.


Man kan också tänka att z kan inte vara mindre än x så då kan man räkna bort 2x i gränsen i stället för bara ett x. Antalet tester minskar inte men antalet loopade tal minskar.

In [5]:
import math as m

max = 100
c = 0
l = 0

for x in range(1, int(max/2)):
    for y in range(1, max - 2*x + 1):
        l += 1
        z2 = x*x + y*y
        z=int(m.sqrt(z2))
        if x+y+z <= max:
            c += 1
            if z2/z == z:
                print(x, y, z)
print("Undersökt ", c, " tal")
print("Loopat ", l, " tal")

3 4 5
4 3 5
5 12 13
6 8 10
7 24 25
8 6 10
8 15 17
9 12 15
9 40 41
10 24 26
12 5 13
12 9 15
12 16 20
12 35 37
15 8 17
15 20 25
15 36 39
16 12 20
16 30 34
18 24 30
20 15 25
20 21 29
21 20 29
21 28 35
24 7 25
24 10 26
24 18 30
24 32 40
28 21 35
30 16 34
32 24 40
35 12 37
36 15 39
40 9 41
Undersökt  1513  tal
Loopat  2450  tal

Utifrån symmetri kan vi också säga att vi inte ska undersöka y som är mindre än eller lika med x, det blir bara dubbletter.

In [6]:
import math as m

max = 100
c = 0
l = 0

for x in range(1, int(max/2)):
    for y in range(x, max - 2*x + 1):
        l += 1
        z2 = x*x + y*y
        z = int(m.sqrt(z2))
        if x+y+z <= max:
            c += 1
            if z2/z == z:
                print(x, y, z)
print("Undersökt ", c, " tal")
print("Loopat ", l, " tal")

3 4 5
5 12 13
6 8 10
7 24 25
8 15 17
9 12 15
9 40 41
10 24 26
12 16 20
12 35 37
15 20 25
15 36 39
16 30 34
18 24 30
20 21 29
21 28 35
24 32 40
Undersökt  771  tal
Loopat  1650  tal

De primitiva pythagoreiska tripplarna med summan mindre än 100 finns i listan nedan.
Vi har hittat alla dessa.

(3, 4, 5)  

(5, 12, 13) 

(8, 15, 17) 

(7, 24, 25) 

(20, 21, 29)

(12, 35, 37)

(9, 40, 41) 


Men vi har även fått med s.k. icke-primitiva i vår lista.

6 8 10  =2*(3,4,5)

9 12 15  =3*(3,4,5)

10 24 26  =2*(5,12,13)

12 16 20  =4*(3,4,5)

15 20 25  =5*(3,4,5) 

15 36 39  =3*(5,12,13)

16 30 34  =2*(8,15,17)

18 24 30  =6*(3,4,5)

21 28 35  =7*(3,4,5)

24 32 40  =8*(3,4,5)